# Winget installer manifest
# Version and hashes updated by release.yml workflow.
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.12.0.schema.json

PackageIdentifier: KopioRapido.KopioRapido
PackageVersion: 2026.08.22
MinimumOSVersion: 10.0.17763.0
InstallerType: zip
NestedInstallerType: portable
NestedInstallerFiles:
  - RelativeFilePath: kp.exe
    PortableCommandAlias: kp
Commands:
  - kp
  - kopiorapido
Dependencies:
  PackageDependencies: []
Installers:
  - Architecture: x64
    InstallerUrl: https://releases.kopiorapido.com/2026.08.22/cli/kopiorapido-cli-win-x64-2026.08.22.zip
    InstallerSha256: d59a74a8bd797e09af06dff51b5a38ecc980c68414bbcd0ca603e6b6939f79da
  - Architecture: arm64
    InstallerUrl: https://releases.kopiorapido.com/2026.08.22/cli/kopiorapido-cli-win-arm64-2026.08.22.zip
    InstallerSha256: 8d6b9c1ab261814e9f99c9465189ba8d54bc695825fb37736441152e4bb8be6a
ManifestType: installer
ManifestVersion: 1.12.0
